# НАУКА О ДАННЫХ НА ЯЗЫКЕ PYTHON

## (DATA SCIENCE WITH PYTHON)

## Стек научных библиотек

## numpy - алгебраические операции с массивами
## pandas - манипулирование данными
## matplotlib - визуализация
## scikit-learn - машинное обучение

# 1. Что там "под капотом"? Некоторые возможности библиотеки ***numpy***

### 1.1. Импортируем библиотеку ***numpy***

In [1]:
import numpy as np

### 1.2. Создаем объекты ***numpy***: 
### 1.2.1. Векторы (одномерные массивы)

In [2]:
# СОЗДАЕМ "НУЛЕВОЙ" ВЕКТОР (ДЛИНОЙ 5)
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [3]:
# СОЗДАЕМ "ЕДИНИЧНЫЙ" ВЕКТОР (ДЛИНОЙ 7)
np.ones(7)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [4]:
# СОЗДАЕМ ВЕКТОР ЗНАЧЕНИЙ ОТ 0 ДО 8 (ДЛИНОЙ 9)
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
# СОЗДАЕМ ВЕКТОР СЛУЧАЙНЫХ ЗНАЧЕНИЙ (ДЛИНОЙ 15)
np.random.random(15)

array([ 0.52477823,  0.1614405 ,  0.97844511,  0.37169282,  0.04301004,
        0.59113775,  0.40316717,  0.69400921,  0.94844295,  0.52484086,
        0.7385348 ,  0.36341472,  0.68356777,  0.90097992,  0.64403152])

### 1.2.2. Матрицы (двумерные массивы)

In [6]:
# СОЗДАЕМ "ЕДИНИЧНУЮ" МАТРИЦУ (РАЗМЕРНОСТЬЮ 5 Х 7)
np.ones(35).reshape(5,7)

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [7]:
# СОЗДАЕМ МАТРИЦУ С ВЫБРАННЫМ ЗНАЧЕНИЕМ (РАЗМЕРНОСТЬЮ 3 Х 5)
np.full((3,5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [8]:
# СОЗДАЕМ МАТРИЦУ СЛУЧАЙНЫХ ЗНАЧЕНИЙ (РАЗМЕРНОСТЬЮ 3 Х 5)
np.random.normal(0,1,15).reshape(3,5)

array([[-0.01652478, -0.59622377,  0.49781535,  0.18118042, -2.29133124],
       [ 0.42322411, -2.14253071,  1.5323083 ,  1.33433936, -0.1910324 ],
       [ 0.34541381, -0.8155812 , -1.05064861,  0.20565215,  0.36088226]])

### 1.2.3. Тензоры (многомерные массивы)

In [9]:
# СОЗДАЕМ МАССИВ ИЗ СЛУЧАЙНОЙ ВЫБОРКИ НОРМАЛЬНО РАСПРЕДЕЛЕННЫХ ЧИСЕЛ В ДИАПАЗОНЕ 10 
# (РАЗМЕРНОСТЬЮ 2 х 3 х 4: МАССИВ ИЗ ДВУХ МАТРИЦ РАЗМЕРНОСТЬЮ 3 х 4) 
np.random.normal(10, size=(2, 3, 4))

array([[[ 11.64455918,  10.55346591,  11.46241239,  10.77668277],
        [  7.35949493,  10.28646733,   9.23120875,  10.74785863],
        [  9.79953406,   9.06923475,   8.60714169,  11.85630274]],

       [[  8.82303007,  11.19909734,   8.42270933,   9.70379025],
        [  9.5838579 ,  11.68848544,  10.08481226,  11.66685154],
        [ 10.62880475,   8.81601184,  11.95948984,  10.92007307]]])

In [10]:
# СОЗДАЕМ МАССИВ ИЗ СЛУЧАЙНОЙ ВЫБОРКИ ЦЕЛЫХ ЧИСЕЛ В ТОМ ЖЕ ДИАПАЗОНЕ 10 
# (РАЗМЕРНОСТЬЮ 2 х 3 х 4 х 5: ДВА МАССИВА ПО ТРИ МАТРИЦЫ РАЗМЕРНОСТЬЮ 4 Х 5)
np.random.randint(10, size=(2, 3, 4, 5))

array([[[[1, 1, 4, 0, 9],
         [4, 4, 9, 3, 1],
         [0, 4, 1, 9, 8],
         [9, 7, 3, 5, 4]],

        [[4, 5, 1, 3, 7],
         [3, 9, 4, 4, 9],
         [8, 0, 5, 9, 4],
         [8, 8, 0, 4, 4]],

        [[9, 4, 1, 0, 2],
         [6, 2, 0, 0, 7],
         [1, 2, 8, 7, 5],
         [7, 1, 9, 3, 6]]],


       [[[4, 2, 6, 2, 7],
         [5, 1, 8, 3, 8],
         [5, 9, 1, 8, 9],
         [8, 2, 5, 7, 0]],

        [[1, 0, 9, 9, 4],
         [4, 0, 7, 6, 2],
         [4, 1, 2, 5, 8],
         [1, 9, 3, 4, 7]],

        [[6, 7, 8, 6, 5],
         [9, 7, 9, 5, 9],
         [7, 0, 6, 1, 1],
         [1, 6, 4, 6, 0]]]])

### 1.3. Получение информации об объектах ***numpy***

In [11]:
# СОЗДАЕМ МАССИВ (РАЗМЕРНОСТЬЮ 5 x 5 ИЗ СГЕНЕРИРОВАННЫХ ЗНАЧЕНИЙ В ДИАПАЗОНЕ [2:100) С ШАГОМ 2)
X = np.array([i for i in range(2,100, 4)]).reshape(5, 5)
X

array([[ 2,  6, 10, 14, 18],
       [22, 26, 30, 34, 38],
       [42, 46, 50, 54, 58],
       [62, 66, 70, 74, 78],
       [82, 86, 90, 94, 98]])

In [12]:
# ВЫВОДИМ РАЗМЕРНОСТЬ МАССИВА (ЧИСЛО ИЗМЕРЕНИЙ)
X.ndim

2

In [13]:
# ВЫВОДИМ ОБЪЕМ МАССИВА (ЧИСЛО ЕДИНИЦ)
X.size

25

In [14]:
# ВЫВОДИМ ФОРМАТ МАССИВА (ЧИСЛО СТРОК Х ЧИСЛО СТОЛБЦОВ)
X.shape

(5, 5)

In [15]:
# ВЫВОДИМ ТИП ПЕРЕМЕННОЙ, ЗАПОЛНЯЮЩЕЙ МАССИВ(ЦЕЛОЕ ИЛИ ВЕЩЕСТВЕННОЕ ЧИСЛО, СИМВОЛ, ЛОГИЧЕСКОЕ ЗНАЧЕНИЕ)
X.dtype

dtype('int32')

In [16]:
# ВОСПРОИЗВОДИМ АНАЛИЗИРУЕМЫЙ МАССИВ
print(X)

[[ 2  6 10 14 18]
 [22 26 30 34 38]
 [42 46 50 54 58]
 [62 66 70 74 78]
 [82 86 90 94 98]]


In [17]:
# ПОЛУЧАЕМ ПОДМАССИВ (ИНАЧЕ, "СРЕЗ") ИЗ ИСХОДНОГО МАССИВА (C 1-Й СТРОКИ ВКЛЮЧИТЕЛЬНО ДО 3-Й СТРОКИ
# НЕВКЛЮЧИТЕЛЬНО И С 0-ГО СТОЛБЦА ВКЛЮЧИТЕЛЬНО ДО 2-ГО СТОЛБЦА НЕВКЛЮЧИТЕЛЬНО)
X_subset_row_1_3_col_0_2 = X[1:3, 0:2]
X_subset_row_1_3_col_0_2

array([[22, 26],
       [42, 46]])

In [18]:
# ПОЛУЧАЕМ ОТДЕЛЬНОЕ ЗНАЧЕНИЕ (ПОДМАССИВ РАЗМЕРНОСТЬЮ 1 х 1) ИЗ ИСХОДНОГО МАССИВА
# (НАХОДЯЩЕЕСЯ НА ПЕРЕСЕЧЕНИИ 1-Й СТРОКИ И 0-ГО СТОЛБЦА)
X_subset_row_1_col_0 = X[1,0]
X_subset_row_1_col_0

22

### 1.4. Операции с объектами ***numpy***

In [19]:
# ЗАПОЛНЯЕМ МАССИВ ЗНАЧЕНИЯМИ ПО СТРОКАМ
X_horizont = np.arange(10).reshape(2, 5)
X_horizont

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
# УМНОЖАЕМ МАССИВ НА ЧИСЛО
X * 10

array([[ 20,  60, 100, 140, 180],
       [220, 260, 300, 340, 380],
       [420, 460, 500, 540, 580],
       [620, 660, 700, 740, 780],
       [820, 860, 900, 940, 980]])

In [21]:
# ЗАПОЛНЯЕМ МАССИВ ЗНАЧЕНИЯМИ ПО СТОЛБЦАМ - ЭТО НЕ ТРАНСПОНИРОВНИЕ!!!
X_vertical = X_horizont.reshape(5, 2)
X_vertical

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
# ПРОИЗВОДИМ СОРТИРОВКУ ЗНАЧЕНИЙ МАССИВА
x_unsort = np.random.randint(1, 10, 10)
print('\nИзначальный (неотсортированный) массив: {}'.format(x_unsort), '\n')
x_sort = np.sort(x_unsort)
print('Отсортированный массив: {}'.format(x_sort), '\n')


Изначальный (неотсортированный) массив: [5 8 9 6 1 2 1 4 8 3] 

Отсортированный массив: [1 1 2 3 4 5 6 8 8 9] 



In [23]:
# НАХОДИМ МИНИМАЛЬНОЕ, СРЕДНЕЕ И МАКСИМАЛЬНОЕ ЗНАЧЕНИЯ ЭЛЕМЕНТОВ В МАССИВЕ
print('Минимальное значение: {mini}; \n\nсреднее значение: {aver}; \n\nмаксимальное значение: {maxi}'
      .format(mini=np.min(X), aver=np.mean(X), maxi=np.max(X)))

Минимальное значение: 2; 

среднее значение: 50.0; 

максимальное значение: 98


In [24]:
# ПРОИЗВОДИМ ПОЭЛЕМЕНТНОЕ СЛОЖЕНИЕ МАССИВОВ - ЭТО НЕ СЛОЖЕНИЕ МАТРИЦ!!!
a = np.arange(3).reshape(3, 1)
b = np.arange(3)
c = a + b
print(a, '\n')
print(b, '\n')
print(c)

[[0]
 [1]
 [2]] 

[0 1 2] 

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [25]:
# ПРОИЗВОДИМ ПОЭЛЕМЕНТНОЕ УМНОЖЕНИЕ МАССИВОВ - ЭТО НЕ УМНОЖЕНИЕ МАТРИЦ!!!
a * b

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [26]:
# ВОЗВЕДЕНИЕ В СТЕПЕНЬ ЭЛЕМЕНТОВ МАССИВА
np.power(a * b, 2)

array([[ 0,  0,  0],
       [ 0,  1,  4],
       [ 0,  4, 16]], dtype=int32)

In [27]:
# НАХОЖДЕНИЕ ТРИГОНОМЕТРИЧЕСКИХ ФУНКЦИЙ
print('Значения синуса для элементов массива а: \n{}'.format(np.sin(a)))

print('Значения косинуса для элементов массива b: \n{}'.format(np.cos(b).reshape(b.shape[0], 1)))

Значения синуса для элементов массива а: 
[[ 0.        ]
 [ 0.84147098]
 [ 0.90929743]]
Значения косинуса для элементов массива b: 
[[ 1.        ]
 [ 0.54030231]
 [-0.41614684]]


In [28]:
# НАХОЖДЕНИЕ ЛОГАРИФМОВ ПО РАЗЛИЧНЫМ ОСНОВАНИЯМ
c = np.array([5,7,9])
print('Логарифмы числа С: \nа) по основанию два {}; \nб) натуральный {}; \nв) десятичный {}'
      .format(np.log2(c), np.log(c), np.log10(c)))

Логарифмы числа С: 
а) по основанию два [ 2.32192809  2.80735492  3.169925  ]; 
б) натуральный [ 1.60943791  1.94591015  2.19722458]; 
в) десятичный [ 0.69897     0.84509804  0.95424251]


### 1.4.1. Матричный режим

In [29]:
# СОЗДАЕМ ТРИ МАТРИЦЫ (ДВЕ МАТРИЦЫ И ОДИН ВЕКТОР-СТОЛБЕЦ)
A = np.arange(12).reshape(3, 4)
B = np.arange(13, 25).reshape(3,4)
C = np.arange(4).reshape(4,1)
D = np.arange(4)
print('Матрица А размерностью 3 х 4: \n{}'.format(A), '\n')
print('Матрица B размерностью 3 х 4: \n{}'.format(B), '\n')
print('Матрица C размерностью 4 x 1 (вектор-столбец): \n{}'.format(C), '\n')
print('Одномерный массив длиною 4: %s' %D, '\n')

Матрица А размерностью 3 х 4: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Матрица B размерностью 3 х 4: 
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 

Матрица C размерностью 4 x 1 (вектор-столбец): 
[[0]
 [1]
 [2]
 [3]] 

Одномерный массив длиною 4: [0 1 2 3] 



In [30]:
# ТРАНСПОНИРУЕМ МАТРИЦУ А (РАЗМЕРНОСТЬЮ 3 Х 4) И ПОЛУЧАЕМ МАТРИЦУ Аt (РАЗМЕРНОСТЬЮ 4 Х 3)
np.transpose(A)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [31]:
# ТРАНСПОРИНУЕМ ВЕКТОР-СТОЛБЕЦ С (МАТРИЦУ РАЗМЕРНОСТЬЮ 4 Х 1) И ПОЛУЧАЕМ ВЕКТОР-СТРОКУ
print(C)
print(np.transpose(C))

[[0]
 [1]
 [2]
 [3]]
[[0 1 2 3]]


In [32]:
# ТРАНСПОНИРУЕМ ОДНОМЕРНЫЙ МАССИВ D - БЕЗРЕЗУЛЬТАТНО
print(D)
print(np.transpose(D))

[0 1 2 3]
[0 1 2 3]


In [33]:
# УМНОЖАЕМ МАТРИЦУ А (РАЗМЕРНОСТЬЮ 3 Х 4) НА МАТРИЦУ С (РАЗМЕРНОСТЬЮ 4 Х 1) И ПОЛУЧАЕМ ВЕКТОР-СТОЛБЕЦ 
# (МАТРИЦУ РАЗМЕРНОСТЬЮ 4 Х 1)
np.dot(A, C)

array([[14],
       [38],
       [62]])

In [34]:
# СОЗДАЕМ КВАДРАТНУЮ МАТРИЦУ И НАХОДИМ ЕЕ ОБРАТНУЮ МАТРИЦУ
E = np.array([3,5,7,11]).reshape(2,2)
E_inv = np.linalg.inv(E)
print('Исходная матрица Е: \n{} \n\nОбратная матрица E_inv: \n{}'.format(E, E_inv))

Исходная матрица Е: 
[[ 3  5]
 [ 7 11]] 

Обратная матрица E_inv: 
[[-5.5  2.5]
 [ 3.5 -1.5]]


In [35]:
# ПЕРЕМНОЖАЕМ ИСХОДНУЮ И ОБРАТНУЮ ЕЙ МАТРИЦЫ И ПОЛУЧАЕМ ЕДИНИЧНУЮ МАТРИЦУ
print(np.dot(E, E_inv))

[[  1.00000000e+00  -8.88178420e-16]
 [  0.00000000e+00   1.00000000e+00]]


In [36]:
# ВЫЧИСЛЯЕМ ОПРЕДЕЛИТЕЛЬ МАТРИЦЫ Е
np.linalg.det(E)

-1.9999999999999989

In [37]:
# ВВЕДЕМ ВЕКТОР-СТОЛБЕЦ С ЧИСЛОМ СТРОК, РАВНЫМ ЧИСЛУ СТОЛБЦОВ МАТРИЦЫ Е
F = np.array([2,4])
F.shape

(2,)

In [38]:
# НАХОДИМ КОРНИ СИСТЕМЫ УРАВНЕНИЙ: Ex = F 
# 3 * x1 + 5 * x2 = 2
# 7 * x1 + 11 * x2 = 4

routs = np.linalg.solve(E,F)
print('\nКорни системы уравнений: x1 = {x1:.3f}; x2 = {x2:.3f}\n'.format(x1=routs[0], x2=routs[1]))


Корни системы уравнений: x1 = -1.000; x2 = 1.000



### Переходим к ***pandas*** 